const pokemons = [
    {
        "pokedex_id":       1,
        "name":             "bulbasaur",
        "description":      "Bulbasaur is a Grass/Poison type Pokémon introduced in Generation 1. Bulbasaur is a small, mainly turquoise amphibian Pokémon with red eyes and a green bulb on its back. It is based on a frog/toad, with the bulb resembling a plant bulb that grows into a flower as it evolves. Bulbasaur is notable for being the very first Pokémon in the National Pokédex. It is one of the three choices for a starter Pokémon in the original Game Boy games, Pokémon Red & Blue (Red & Green in Japan), along with Charmander and Squirtle.",
        "species":          "Seed Pokémon",
        "height":           0.7,
        "weight":           6.9,
        "baseStats": {
            "hp":           45,
            "attack":       49,
            "defense":      49,
            "sp.attack":    65,
            "sp.defense":   65,
            "speed":        45,
        },
    },
    {
        "pokedex_id":       2,
        "name":             "ivysaur",
        "description":      "Ivysaur is a Grass/Poison type Pokémon introduced in Generation 1.",
        "species":          "Seed Pokémon",
        "height":           1,
        "weight":           13,
        "baseStats": {
            "hp":           60,
            "attack":       62,
            "defense":      63,
            "sp.attack":    80,
            "sp.defense":   80,
            "speed":        60,
        },
    },
    {
        "pokedex_id":       3,
        "name":             "venusaur",
        "description":      "Venusaur is a Grass/Poison type Pokémon introduced in Generation 1. Venusaur is a large, quadrupedal Pokémon with a turquoise body. It has small red eyes and several large ferns on its back and head. The plant bulb that was on the back of its previous evolutions, Bulbasaur and Ivysaur, has now bloomed into a large flower with large pink petals and a yellow center. The female has a seed in the center. Venusaur is inspired by toads and the horned frog. The large flower is similar to the Rafflesia arnoldii, a parasitic plant with an unpleasant odor, referencing the Pokémon's Poison type. Venusaur is notable for being the final evolution stage of one of the original starter Pokémon, along with Charizard and Blastoise. It has a Mega Evolution, available in Generation 6 games and Pokémon Go; it also has a Gigantamax form available in Pokémon Sword/Shield, with an exclusive G-Max move, G-Max Vine Lash.",
        "species":          "Seed Pokémon",
        "height":           2,
        "weight":           100,
        "baseStats": {
            "hp":           80,
            "attack":       82,
            "defense":      83,
            "sp.attack":    100,
            "sp.defense":   100,
            "speed":        80,
        },
    },
    {
        "pokedex_id":       4,
        "name":             "Charmander",
        "description":      "Charmander is a Fire type Pokémon introduced in Generation 1. Charmander is a bipedal, reptilian Pokémon. Most of its body is colored orange, while its underbelly is light yellow and it has blue eyes. It has a flame at the end of its tail, which is said to signify its health. Charmander's design is based on a lizard, however as its name suggests it may also have been inspired by salamanders, which in mythology have an affinity with fire. Charmander is notable for being one of the three choices for a starter Pokémon in the original Game Boy games, Pokémon Red & Blue (Red & Green in Japan), along with Bulbasaur and Squirtle.",
        "species":          "Lizard Pokémon",
        "height":           0.6,
        "weight":           8.5,
        "baseStats": {
            "hp":           39,
            "attack":       52,
            "defense":      43,
            "sp.attack":    60,
            "sp.defense":   50,
            "speed":        65,
        },
    },
    {
        "pokedex_id":       5,
        "name":             "charmeleon",
        "description":      "Charmeleon is a Fire type Pokémon introduced in Generation 1.",
        "species":          "Flame Pokémon",
        "height":           1.1,
        "weight":           19,
        "baseStats": {
            "hp":           58,
            "attack":       64,
            "defense":      58,
            "sp.attack":    80,
            "sp.defense":   65,
            "speed":        80,
        },
    },
    {
        "pokedex_id":       6,
        "name":             "charizard",
        "description":      "Charizard is a Fire/Flying type Pokémon introduced in Generation 1. Charizard is a large dragon-like Pokémon, mainly orange in color. It has two large wings, the underside of which are turquoise. Like Charmander and Charmeleon, it has a flame at the end of its tail. The design of Charizard appears to draw inspiration from dragons of European folklore, with its large wings, horned head, and fiery breath. Charizard is notable for being the final evolution stage of one of the original starter Pokémon, along with Venusaur and Blastoise. Although it looks like a dragon, it doesn't have the Dragon typing. However it has two Mega Evolutions, available in Generation 6 games and Pokémon Go, one of which replaces its Flying type with Dragon. Charizard also has a Gigantamax form available in Pokémon Sword/Shield, with an exclusive G-Max move, G-Max Wildfire.",
        "species":          "Flame Pokémon",
        "height":           1.7,
        "weight":           90.5,
        "baseStats": {
            "hp":           78,
            "attack":       84,
            "defense":      78,
            "sp.attack":    109,
            "sp.defense":   85,
            "speed":        100,
        },
    },
    {
        "pokedex_id":       7,
        "name":             "squirtle",
        "description":      "Squirtle is a Water type Pokémon introduced in Generation 1. Squirtle is a bipedal, reptilian Pokémon. It has a blue body with purple eyes, a light brown belly, and a tough red-brown shell on its back. It has a long tail that curls into a spiral. Squirtle is primarily based on a turtle, taking inspiration from both land-dwelling and sea-dwelling varieties. The curly tail resembles a crashing wave. Squirtle is notable for being one of the three choices for a starter Pokémon in the original Game Boy games, Pokémon Red & Blue (Red & Green in Japan), along with Bulbasaur and Charmander.",
        "species":          "Tiny Turtle Pokémon",
        "height":           0.5,
        "weight":           9,
        "baseStats": {
            "hp":           44,
            "attack":       48,
            "defense":      65,
            "sp.attack":    50,
            "sp.defense":   64,
            "speed":        43,
        },
    },
    {
        "pokedex_id":       8,
        "name":             "wartortle",
        "description":      "Wartortle is a Water type Pokémon introduced in Generation 1.",
        "species":          "Turtle Pokémon",
        "height":           1,
        "weight":           22.5,
        "baseStats": {
            "hp":           59,
            "attack":       63,
            "defense":      80,
            "sp.attack":    65,
            "sp.defense":   80,
            "speed":        58,
        },
    },
    {
        "pokedex_id":       9,
        "name":             "blastoise",
        "description":      "Blastoise is a Water type Pokémon introduced in Generation 1. Blastoise is a large, bipedal, reptilian Pokémon. It has a blue body with small purple eyes, a light brown belly, and a stubby tail. It has a large brown shell with two powerful water cannons on either side, which can be withdrawn. Blastoise's design is heavily influenced by turtles and tortoises. The cannons likely draw inspiration from the concept of a mobile tank or battleship. Blastoise is notable for being the final evolution stage of one of the original starter Pokémon, along with Venusaur and Charizard. It has a Mega Evolution, available in Generation 6 games and Pokémon Go; it also has a Gigantamax form available in Pokémon Sword/Shield, with an exclusive G-Max move, G-Max Cannonade.",
        "species":          "Shellfish Pokémon",
        "height":           1.6,
        "weight":           85.5,
        "baseStats": {
            "hp":           79,
            "attack":       83,
            "defense":      100,
            "sp.attack":    85,
            "sp.defense":   105,
            "speed":        78,
        },
    },
];

export default pokemons;